name: test
channels:
  - robostack-jazzy
  - conda-forge
dependencies:
  - cxx-compiler
  - ninja
  - cmake
  - pkg-config
  - rosdep
  - rosdistro
  - colcon-common-extensions
  - ros-jazzy-ros-workspace
